[tool.black]
line-length = 100

[tool.ruff]
fix = false
fixable = [
  "I001", # isort (sorting)
  "F", # flake8
  "D", # docformatter
  "UP", # pyupgrade
]
ignore = [
  "D1", # D1: Missing docstring error codes (because not every function and class has a docstring)
  "D203", # D203: 1 blank line required before class docstring (conflicts with D211 and should be disabled, see https://github.com/PyCQA/pydocstyle/pull/91)
  "D205",
  "D212", # D212: Multi-line docstring summary should start at the first line
]
line-length = 120
select = [
  "D", # pydocstyle
  "E", # pycodestyle
  "F", # flake8
  "I", # isort
  "UP", # pyupgrade
]
target-version = "py311"
unfixable = [
  "F8", # names in flake8, such as defined but unused variables
]

[tool.ruff.per-file-ignores]
"*/migrations/*" = ["D417", "E501"]

[tool.djlint]
# Reference: https://djlint.com/djlint/rules.html
blank_line_after_tag = "load,extends,endblock,has_perm"
ignore = "H006,H008,H013,H014,H017,H019,H021,H023,T001,T002,T003"
max_line_length = 120
profile = "django"
